public enum TokenType {
    LET, BE, PRINT, IF, THEN, OTHERWISE,
    IS_EQUAL_TO, IS_GREATER_THAN, IS_LESS_THAN,
    IDENTIFIER, NUMBER, STRING,
    ADD, SUBTRACT, MULTIPLY, DIVIDE, COMMENT,REPEAT, TIMES, WHILE,
    FUNCTION, CALL,
    LBRACE, RBRACE,
    EOF
}
